# Práctica #6 Redes nueronales (SCKIT) estandarizados

### En esta práctica implementamos un modelo de clasificación utilizando una red neuronal con la técnica de propagación hacia atrás (NNBP). La red se implement+o utilizando la librería de código abierto SCIKIT*LEARN, y la clase MLP Classifier(). Se van a estandarizar los datos para mejorar el procesamiento del clasificador

## Librerías

In [1]:
import os
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import confusion_matrix
from sklearn.preprocessing import StandardScaler

## Cargar el dataset

In [2]:
datos = pd.read_csv(filepath_or_buffer="iris.csv", delimiter=";")
print(datos.shape)
print(datos.head())

(150, 5)
   s.largo  s.ancho  p.largo  p.ancho    tipo
0      5.1      3.5      1.4      0.2  setosa
1      4.9      3.0      1.4      0.2  setosa
2      4.7      3.2      1.3      0.2  setosa
3      4.6      3.1      1.5      0.2  setosa
4      5.0      3.6      1.4      0.2  setosa


#### Eliminar variable predictora de X

In [3]:
X = datos.iloc[:, :4]
X.head()

s.largo  s.ancho  p.largo  p.ancho
0      5.1      3.5      1.4      0.2
1      4.9      3.0      1.4      0.2
2      4.7      3.2      1.3      0.2
3      4.6      3.1      1.5      0.2
4      5.0      3.6      1.4      0.2

## Normalizar datos

### Utilizamos la clase StandardScaler para normalizar los datos

In [6]:
datos.iloc[:, 0:4] = StandardScaler().fit_transform(datos.iloc[:, 0:4])
datos.head()

s.largo   s.ancho   p.largo   p.ancho    tipo
0 -0.900681  1.032057 -1.341272 -1.312977  setosa
1 -1.143017 -0.124958 -1.341272 -1.312977  setosa
2 -1.385353  0.337848 -1.398138 -1.312977  setosa
3 -1.506521  0.106445 -1.284407 -1.312977  setosa
4 -1.021849  1.263460 -1.341272 -1.312977  setosa

#### Extraer variable a predecir en y

In [4]:
y = datos.iloc[: , 4:]
y.head()

tipo
0  setosa
1  setosa
2  setosa
3  setosa
4  setosa

#### Se separan los datos en train (70%) y test (80%)

In [5]:
X_train, X_test, y_train, y_test = train_test_split(X,y, train_size=0.7, random_state=42)

#### Mediante el constructor inicializa la instancia de la red

Nota: Por defecto usa 100 nodos en cada capa oculta, "solver" es el método de optimización

In [6]:
instancia_red = MLPClassifier()
print(instancia_red)

MLPClassifier()


#### Entrenamiento del modelo

In [7]:
print(X_train.iloc[:,0].values)
print(X_train)
instancia_red.fit(X_train, y_train.iloc[:,0].values)

[5.5 6.3 6.4 6.6 7.2 5.7 7.6 5.6 5.1 7.7 5.8 5.2 5.  5.1 5.  6.3 4.8 5.
 5.1 5.6 5.1 5.7 7.7 4.6 6.2 5.7 5.5 6.  5.8 6.  5.4 6.2 5.5 5.4 5.  6.4
 5.  5.  5.5 6.7 4.9 5.8 5.  5.  5.9 5.1 6.9 6.  6.1 7.7 5.5 4.4 4.3 6.
 7.2 4.6 5.1 4.4 6.3 6.3 4.6 6.8 6.3 4.7 6.1 6.5 6.2 7.  6.4 5.1 6.9 5.9
 6.5 5.7 5.2 6.1 4.5 6.6 5.5 5.3 5.6 7.3 6.7 5.1 4.9 6.7 7.2 4.9 6.7 4.9
 6.9 7.4 6.3 5.7 6.5 6.3 6.4 5.6 5.9 5.4 6.1 4.9 5.8 5.8 7.1]
     s.largo  s.ancho  p.largo  p.ancho
81       5.5      2.4      3.7      1.0
133      6.3      2.8      5.1      1.5
137      6.4      3.1      5.5      1.8
75       6.6      3.0      4.4      1.4
109      7.2      3.6      6.1      2.5
..       ...      ...      ...      ...
71       6.1      2.8      4.0      1.3
106      4.9      2.5      4.5      1.7
14       5.8      4.0      1.2      0.2
92       5.8      2.6      4.0      1.2
102      7.1      3.0      5.9      2.1

[105 rows x 4 columns]


d:\Python\Python 3.11\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


MLPClassifier()

In [8]:
print("Las predicciones del testing son: {}".format(instancia_red.predict(X_test)))

Las predicciones del testing son: ['versicolor' 'setosa' 'virginica' 'versicolor' 'versicolor' 'setosa'
 'versicolor' 'virginica' 'versicolor' 'versicolor' 'virginica' 'setosa'
 'setosa' 'setosa' 'setosa' 'versicolor' 'virginica' 'versicolor'
 'versicolor' 'virginica' 'setosa' 'virginica' 'setosa' 'virginica'
 'virginica' 'virginica' 'virginica' 'virginica' 'setosa' 'setosa'
 'setosa' 'setosa' 'versicolor' 'setosa' 'setosa' 'virginica' 'versicolor'
 'setosa' 'setosa' 'setosa' 'virginica' 'versicolor' 'versicolor' 'setosa'
 'setosa']


#### Funcion para calcular que tan bueno es el modelo

In [9]:
def indices_general(MC, nombres=None):
    precision_global = np.sum(MC.diagonal()) / np.sum(MC)
    error_global = 1 - precision_global
    precision_categorica = pd.DataFrame(MC.diagonal()/np.sum(MC,axis=1)).T
    if nombres != None:
        precision_categorica.columns = nombres
    return {
        "Matriz de confusion": MC,
        "Precision global": precision_global,
        "Error global": error_global,
        "Precision por categoria": precision_categorica
    }

#### Indices de calidad del modelo

In [10]:
prediccion = instancia_red.predict(X_test)
MC = confusion_matrix(y_test, prediccion)
indices = indices_general(MC,list(np.unique(y)))
for k in indices:
    print("\n%s:\n%s"%(k,str(indices[k])))


Matriz de confusion:
[[19  0  0]
 [ 0 13  0]
 [ 0  0 13]]

Precision global:
1.0

Error global:
0.0

Precision por categoria:
   setosa  versicolor  virginica
0     1.0         1.0        1.0


### Conclusión

En esta práctica utilizamos un algoritmo de aprendizaje automático para clasificar clases de las flores de iris. Utlizando las Redes neuronales de propagación hacia atrás, utilizamos las características de longitud y ancho del pétalo, y longitud y ancho del séfalo.

<p>URL: SCKIT-LEARN (Machine learning python 2024): <a href="https://scikit-learn.org/stable/modules/generated/sklearn.neural_network.MLPClassifier.html">https://scikit-learn.org/stable/modules/generated/sklearn.neural_network.MLPClassifier.html</a></p>