<p>06 de marzo de 2024</p>
<p>Universidad Autónoma de Aguascalientes</p>
<p>Departamento: Ciencias de la computación</p>
<p>Carrera: Ingeniería en Computación Inteligente</p>
<p>Maestro: Dr. Francisco Javier Luna Rosas</p>
<p>Curso: Machine learning y deep learning</p>
<p>Alumno: Antonio Muñoz Barrientos</p>
<p>Semestre Enero - junio 2024</p>

## Practca # 8 - Componentes matemáticos de deep learning (Tensores 0D, 1D, 2D, 3D, 4D, ...)

In [1]:
import numpy as np

#### Escalares

Un tensor que solo tenga un elemento (0D)

In [3]:
x = np.array(2)
x

array(2)

In [5]:
# Dimensiones de X
x.ndim

0

#### Tensores (1D)

In [6]:
x = np.array([12,36,8,4,5])
x

array([12, 36,  8,  4,  5])

_Nota_: Un vector de 5 dimensiones no es igual a un tensor de 5 dimensiones

In [7]:
# Dimensiones de x
x.ndim

1

#### Tensores (2D) Matrices

In [9]:
x = np.array([[1,4,5,6,7], [8,8494,5615,6465,8],[1,4,5,6,7]])
x

array([[   1,    4,    5,    6,    7],
       [   8, 8494, 5615, 6465,    8],
       [   1,    4,    5,    6,    7]])

In [10]:
# Dimensiones de x
x.ndim

2

#### Tensores (3D) y mas dimensiones

In [11]:
x = np.array([[[1,2,3,4], [5,6,7,8],[9,10,11,12]],
              [[1,2,3,4], [5,6,7,8],[9,10,11,12]],
              [[1,2,3,4], [5,6,7,8],[9,10,11,12]]])
x

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]])

In [12]:
# Dimensiones de x
x.ndim

3

#### Empaquetando tensores 3d formarmos un tensor de 4d, y así sucesivamente

Se pueden hacer tensores de mas dimensiones, pero en deep learning el estimado es de 0D a 4D

In [14]:
x = np.array([
    [[[1,2,3,4], [5,6,7,8],[9,10,11,12]],
              [[1,2,3,4], [5,6,7,8],[9,10,11,12]],
              [[1,2,3,4], [5,6,7,8],[9,10,11,12]]],
    [[[1,2,3,4], [5,6,7,8],[9,10,11,12]],
              [[1,2,3,4], [5,6,7,8],[9,10,11,12]],
              [[1,2,3,4], [5,6,7,8],[9,10,11,12]]],
    [[[1,2,3,4], [5,6,7,8],[9,10,11,12]],
              [[1,2,3,4], [5,6,7,8],[9,10,11,12]],
              [[1,2,3,4], [5,6,7,8],[9,10,11,12]]]
])
x

array([[[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],

        [[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],

        [[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]]],


       [[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],

        [[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],

        [[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]]],


       [[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],

        [[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],

        [[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]]]])

In [15]:
# Dimensiones de X
x.ndim

4

## Conclusiones
Un tensor es un contenedor de datos, casi siempre numérico. Las matrices son tensores en 2d, etc. En deep Learning, generalmente manipularemos tensores desde 0D a 4D.